name: Deploy Docs

on: 
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install deps
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy to gh-pages branch
        run: mkdocs gh-deploy --force